package by.parfen.disptaxi.datamodel.enums;

public enum OrderResult {
	// ORDER CAN'T BE CHANGED
	// ADD ITEMS TO THE END OF LIST ONLY
	// DON'T REMOVE

	ORDERRESULT_NONE, ORDERRESUT_OK, ORDERRESUT_CANCELED, ORDERRESUT_CANCELED_BY_DRIVER, ORDERRESUT_CANCELED_BY_CUSTOMER;

}
